version: "3.9"

services:
  
  rate-app:
    build:
      context: .
      dockerfile: ./rate-app/Dockerfile
    container_name: rate-app
    image: rate-app
    env_file: ./rate-app/.env
    ports:
      - "3000:3000"

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
        - "5672:5672"
        - "15672:15672"
    volumes:
        - /var/lib/rabbitmq