version: "3.9"

services:

  rate-app:
    build:
      context: rate-app
      dockerfile: Dockerfile
    container_name: rate-app
    image: rate-app
    env_file: ./rate-app/.env
    ports:
      - "3000:3000"
    restart: on-failure
    depends_on:
      - rabbitmq
    links:
      - rabbitmq

  logger-app:
    build:
      context: logger-app
      dockerfile: Dockerfile
    container_name: logger-app
    image: logger-app
    env_file: ./logger-app/.env
    ports:
      - "3001:3001"
    restart: on-failure
    depends_on:
      - rabbitmq
    links:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:15672" ]
      interval: 30s
      timeout: 10s
      retries: 5
